# Generated by Django 3.1.2 on 2020-10-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0002_usuario_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='date_created',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='telefone',
        ),
    ]
