# Generated by Django 3.1.2 on 2020-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0004_auto_20201007_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='placar1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='placar2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
