# Generated by Django 3.1.2 on 2020-10-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0005_auto_20201014_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='status',
        ),
    ]
