# Generated by Django 3.1.2 on 2020-10-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0006_remove_aposta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='empate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aposta',
            name='time1Venceu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aposta',
            name='time2Venceu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='empate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='time1Venceu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='time2Venceu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apostas.partida'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='placar1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='placar2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apostas.usuario'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data_partida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='placar2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='saldo',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
