# Generated by Django 3.1.2 on 2020-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0007_auto_20201022_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='time1Venceu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partida',
            name='time2Venceu',
            field=models.BooleanField(default=False),
        ),
    ]
